@startuml

title __Diagramme des classes__\n


    class Arbre {
        + lienVerslePere : String
        + noeud : String
        + parenthesage : ArrayList<Arbre>
        + insertionNiveauArbre()
    }


    class Arbre.Noeud {
        ~ data : int
        ~ Noeud()
    }
  

    class Strand {
        ~ parenthesing : String
        ~ sequence : String
        + Strand()
        + biggestSubstrand()
        + contains()
        + sameParenthesing()
        + sequences_et_formes_egales()
        + strandEgality()
        + testParenthesing()
        + toString()
    }
  

    class StrandBuilder {
        {static} + appariement_corrected_without_extremities()
        {static} + cutExtremities()
        {static} + firstAndLastParenthesis()
        {static} + input_brin()
        {static} + readFile()
        {static} + sequence_corrected_without_extremities()
    }
  

    class Tests {
        {static} + main()
    }
  

    class Tree {
        - children : ArrayList<Tree>
        - label : String
        + Tree()
        + Tree()
        + addChildren()
        + addPair()
        + lastChild()
        + presentInTree()
        {static} + strandToTree()
        + toString()
        + treeToParenthesis()
    }
  

  Arbre +-down- Arbre.Noeud
  Arbre.Noeud o-- Arbre.Noeud : droite
  Arbre.Noeud o-- Arbre.Noeud : gauche
  Tree o-- Tree : linkTofather



@enduml
