@startuml

title __Diagramme des classes__\n

  

    class Strand {
        ~ parenthesing : string
        ~ sequence : string
        + Strand(String sequence, String parenthesing)
        + biggestSubstrand(Strand strandToCompare) : string
        + contains(Strand motif, boolean useSequence) : boolean
        + sameParenthesing(Strand strand) : boolean
        + sequences_et_formes_egales(Strand strand2) : boolean
        + strandEgality(Strand strand2, String methode) : boolean
        + testParenthesing()
        + toString()
    }
  

    class StrandBuilder {
        + appariement_corrected_without_extremities(String appariementToCorrect) : string
        + cutExtremities(int[] positionExtremities, String elementStrand) : string
        + firstAndLastParenthesis(String parenthesing) : int
        + input_brin(String sequence, String parenthesing) : string
        + readFile(String filename) : string
        + sequence_corrected_without_extremities(String sequence_to_correct) : string
    }


    class Tree {
        - children : arrayList<Tree>
        - label : string
        + Tree()
        + Tree(String label, Tree father)
        + addChildren(String label)
        + addPair(String base)
        + lastChild()
        + presentInTree(Tree motif, boolean UseSequence) : boolean
        + strandToTree(Strand RNA)
        + toString() : string
        + treeToParenthesis() : string
    }
  
  Tree -down- StrandBuilder : utilise les séquences
  Strand -right- Tree : utilise les séquences
  Tree o-- Tree : linkTofather



@enduml
